version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_URL:-http://127.0.0.1:5000}
    volumes:
      - ./frontend/src/config.json:/app/src/config.json

