pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/mananshah14/jenkins-cicd-setup.git'
        DOCKER_IMAGE_NAME = 'frontend'
        BACKEND_URL = 'http://127.0.0.1:5000' // You can modify this as needed
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: "${REPO_URL}", branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('frontend') {
                    sh 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE_NAME}")
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                sh 'docker-compose down'
                sh 'docker-compose up -d --build'
            }
        }

    

