pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/mananshah14/jenkins-cicd-setup.git'
        DOCKER_IMAGE_NAME = 'frontend'
        BACKEND_URL = 'http://127.0.0.1:5000' // You can modify this as per your backend IP
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: "${REPO_URL}", branch: 'main'
                echo 'Repository Clone completed'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('demo-fe-be/frontend') {
                    sh 'npm install'
                }
                echo 'Dependencies Installation completed'
            }
        }

        stage('Run Tests') {
            steps {
                dir('demo-fe-be/frontend') {
                    sh 'npm test'
                }
                echo 'Tests Execution completed'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('demo-fe-be/frontend') {
                    script {
                        dockerImage = docker.build("${DOCKER_IMAGE_NAME}")
                    }
                }
                echo 'Docker Image Build completed'
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                script {
                    // Make sure the docker-compose.yml file is in the correct path
                    dir('demo-fe-be/frontend') {
                        sh 'docker-compose down'
                        sh 'docker-compose up -d --build'
                    }
                }
                echo 'Deployment with Docker Compose completed'
            }
        }
    }
}
